fcn_segmentation_node:
  ros__parameters:
    # ROS parameters for the FCN segmentation node
    input_topic: "kitti/camera/color/left/image_raw"
    output_topic: "fcn_segmentation"
    output_overlay_topic: "fcn_segmentation_overlay"
    queue_size: 10  # QoS parameter
    processing_frequency: 50.0  # Hz
    max_processing_queue_size: 3  # Maximum number of queue
    # Model parameters
    engine_file: "fcn_resnet50_1238x374.engine"
    width: 1238
    height: 374
    num_classes: 21
    warmup_iterations: 2 # Warmup iterations for better performance
    log_level: 3  # 0: Internal Error, 1: Error , 2: Warning, 3: Info, 4: Verbose
